#!/usr/bin/env bash
# Displays numbers from 1 to 20 but bad luck from China and good luck from Japan and bad luck from Italy for the 4th ,8th,17th iteration respectively

counter=0

while [ $counter -le 20 ]
do
    
  echo "$counter"
  case $counter in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( counter++ ))
done